# environment configuration
settings:
  docker:
    requirements: requirements.txt
    required_integrations: ["langchain", "openai", "pillow"]

model:
  name: {{project_name}}_model
  license: Apache 2.0
  description: "{{agent_name}} Agent with a vector store tool."
  tags: ["llm", "agent", "rag"]

steps:
  url_scraper:
    enable_cache: False
    parameters:
      docs_url: {{docs_url}}
      website_url: {{website_url}}
      repo_url: {{repo_url}}
  agent_creator:
    enable_cache: False