# environment configuration
enable_cache: false
settings:
  docker:
    required_integrations:
      - xgboost
    requirements:
      - zenml[server]
      - pandas
      - xgboost
      - google-cloud-bigquery
      - pyarrow
      - db-dtypes

# pipeline configuration
model:
  name: ecb_interest_rate_model
  description: An ECB interest rate prediction model
  tags: ["ecb", "interest_rate", "prediction", "xgboost"]


steps:
  extract_data_remote:
    parameters:
      data_path: gs://zenml-internal-artifact-store/raw_data.csv

  transform_bq:
    parameters:
      table_id: zenml-core.ecb_experiments.ecb_transformed_dataset
