enable_cache: False

settings:
  docker:
    apt_packages:
      - ffmpeg
      - libsm6
      - libxext6
    required_integrations:
      - gcp
      - github
    requirements:
      - ultralytics
      - fiftyone

# configuration of the Model Control Plane
model:
  name: Yolo_Object_Detection
  license: Apache 2.0
  description: Object Detection Model.
  tags: ["object detection"]
  version: production