
steps:
  process_hf_dataset:
    enable_cache: True
    enable_step_logs: False
    parameters:
      dataset: "datadrivenscience/ship-detection"
      data_source: <INSERT_HERE>  # Replace this with our path to the data source
  upload_labels_to_label_studio:
    enable_cache: False
    parameters:
      ls_project_id: 8
