
steps:
  process_hf_dataset:
    enable_cache: True
    enable_step_logs: False
    parameters:
      dataset: "datadrivenscience/ship-detection"
      data_source: "gs://zenml-internal-artifact-store/cv_ship_detection"
  upload_labels_to_label_studio:
    enable_cache: False
    parameters:
      ls_project_id: 8
