enable_cache: False

settings:
  docker:
    required_integrations:
      - gcp
      - torch
    requirements:
      - ultralytics

# configuration of the Model Control Plane
model:
  name: YOLO
  license: Apache 2.0
  description: Object Detection Model.
  tags: ["object detection", "customer_satisfaction"]