enable_cache: False

settings:
  docker:
    required_integrations:
      - gcp
      - torch
    requirements:
      - ultralytics

# configuration of the Model Control Plane
model:
  name: Yolo_Object_Detection
  license: Apache 2.0
  description: Object Detection Model.
  tags: ["object detection"]
  version: staging