enable_cache: False

settings:
  docker:
    required_integrations:
      - gcp
    requirements:
      - ultralytics

steps:
  train_model:
    step_operator: gcp_a100
    enable_step_logs: False
    settings:
      docker:
        parent_image: pytorch/pytorch:2.2.0-cuda11.8-cudnn8-runtime
        required_integrations:
          - gcp
        requirements:
          - ultralytics
          - zenml

# configuration of the Model Control Plane
model:
  name: Yolo_Object_Detection
  license: Apache 2.0
  description: Object Detection Model.
  tags: ["object detection"]
  version: staging